package Acme::Lou::Effect;
use strict;
use utf8;

our @html_style = (
'<FONT color=#ff00ff><STRONG>%s</STRONG></FONT>',
'<FONT color=#ff0000><STRONG>%s</STRONG></FONT>',
'<FONT color=#00cc00><STRONG>%s</STRONG></FONT>',
'<FONT color=#cc00ff><STRONG>%s</STRONG></FONT>',
'<FONT color=#ff00ff>%s</FONT>',
'<FONT color=#ff0000>%s</FONT>',
'<FONT color=#00cc00>%s</FONT>',
'<FONT color=#cc00ff>%s</FONT>',
'<FONT color=#ff00ff><STRONG>%s</STRONG></FONT>',
'<FONT color=#ff0000><STRONG>%s</STRONG></FONT>',
'<FONT color=#00cc00><STRONG>%s</STRONG></FONT>',
'<FONT color=#cc00ff><STRONG>%s</STRONG></FONT>',
'<FONT color=#ff00ff size=3>%s</FONT>',
'<FONT color=#ff0000 size=3>%s</FONT>',
'<FONT color=#00cc00 size=3>%s</FONT>',
'<FONT color=#cc00ff size=3>%s</FONT>',
'<FONT color=#ff00ff size=5>%s</FONT>',
'<FONT color=#ff0000 size=5>%s</FONT>',
'<FONT color=#00cc00 size=5>%s</FONT>',
'<FONT color=#cc00ff size=5>%s</FONT>',
'<FONT color=#000000 size=4>%s</FONT>',
'<FONT color=#000000>%s</FONT>',
'<FONT color=#0000cc size=5>%s</FONT>',
'<FONT color=#0000cc size=7>%s</FONT>',
'<FONT color=#0000cc>%s</FONT>',
'<FONT color=#0000ff size=4>%s</FONT>',
'<FONT color=#0000ff size=5><STRONG>%s</STRONG></FONT>',
'<FONT color=#0000ff>%s</FONT>',
'<FONT color=#0000ff><STRONG>%s</STRONG></FONT>',
'<FONT color=#003399 size=5>%s</FONT>',
'<FONT color=#003399>%s</FONT>',
'<FONT color=#00683e size=4><STRONG>%s</STRONG></FONT>',
'<FONT color=#00683e size=5>%s</FONT>',
'<FONT color=#00683e>%s</FONT>',
'<FONT color=#00683e><STRONG>%s</STRONG></FONT>',
'<FONT color=#009f62 size=5>%s</FONT>',
'<FONT color=#009f62><STRONG>%s</STRONG></FONT>',
'<FONT color=#4352c2 size=6>%s</FONT>',
'<FONT color=#4352c2>%s</FONT>',
'<FONT color=#666666 size=5>%s</FONT>',
'<FONT color=#666666>%s</FONT>',
'<FONT color=#6a4f9a>%s</FONT>',
'<FONT color=#800080 size=5>%s</FONT>',
'<FONT color=#800080>%s</FONT>',
'<FONT color=#92007b size=4>%s</FONT>',
'<FONT color=#92007b size=5>%s</FONT>',
'<FONT color=#92007b size=6>%s</FONT>',
'<FONT color=#92007b>%s</FONT>',
'<FONT color=#92007b><STRONG>%s</STRONG></FONT>',
'<FONT color=#990033 size=5>%s</FONT>',
'<FONT color=#df0029 size=4>%s</FONT>',
'<FONT color=#df0029 size=4><STRONG>%s</STRONG></FONT>',
'<FONT color=#df0029 size=5>%s</FONT>',
'<FONT color=#df0029 size=5><EM>%s</EM></FONT>',
'<FONT color=#df0029 size=6>%s</FONT>',
'<FONT color=#df0029 size=7>%s</FONT>',
'<FONT color=#df0029>%s</FONT>',
'<FONT color=#df0029><STRONG>%s</STRONG></FONT>',
'<FONT color=#e2007f size=4>%s</FONT>',
'<FONT color=#e2007f size=4><STRONG>%s</STRONG></FONT>',
'<FONT color=#e2007f size=5>%s</FONT>',
'<FONT color=#e2007f size=6>%s</FONT>',
'<FONT color=#e2007f size=6><EM>%s</EM></FONT>',
'<FONT color=#e2007f>%s</FONT>',
'<FONT color=#e2007f><STRONG>%s</STRONG></FONT>',
'<FONT color=#e69c00 size=4>%s</FONT>',
'<FONT color=#e69c00 size=5>%s</FONT>',
'<FONT color=#e69c00>%s</FONT>',
'<FONT color=#e7651a size=4>%s</FONT>',
'<FONT color=#e7651a size=4><STRONG>%s</STRONG></FONT>',
'<FONT color=#e7651a size=5>%s</FONT>',
'<FONT color=#e7651a size=5>%s</FONT>',
'<FONT color=#e7651a size=5><EM>%s</EM></FONT>',
'<FONT color=#e7651a size=5><STRONG>%s</STRONG></FONT>',
'<FONT color=#e7651a size=6>%s</FONT>',
'<FONT color=#e7651a>%s</FONT>',
'<FONT color=#e7651a><STRONG>%s</STRONG></FONT>',
'<FONT face=魚石行書 color=#990033>%s</FONT>',
'<FONT face=魚石行書 size=5>%s</FONT>',
'<FONT face=HG正楷書体-PRO color=#00683e size=4>%s</FONT>',
'<FONT face=HG正楷書体-PRO color=#df0029 size=5>%s</FONT>',
'<FONT face=HG創英角ﾎﾟｯﾌﾟ体 color=#df0029 size=5>%s</FONT>',
'<FONT face=HGP創英角ﾎﾟｯﾌﾟ体 color=#666666>%s</FONT>',
'<FONT face=HGP創英角ﾎﾟｯﾌﾟ体 color=#0000ff size=5>%s</FONT>',
'<FONT face=HGP創英角ﾎﾟｯﾌﾟ体 color=#92007b size=5><EM>%s</EM></FONT>',
'<FONT face=HGP創英角ﾎﾟｯﾌﾟ体 size=5>%s</FONT>',
'<FONT face=HGP創英角ﾎﾟｯﾌﾟ体 size=6 color=#009F62>%s</FONT>',
'<FONT face=HGP創英角ﾎﾟｯﾌﾟ体 size=6 color=#666666>%s</FONT>',
'<FONT face=HGP創英角ﾎﾟｯﾌﾟ体>%s</FONT>',
'<FONT face=HGS創英角ﾎﾟｯﾌﾟ体 size=5>%s</FONT>',
'<FONT face=HGS創英角ﾎﾟｯﾌﾟ体 color="#e2007f" size="4">%s</FONT>',
'<FONT face=HGS創英角ﾎﾟｯﾌﾟ体>%s</FONT>',
'<FONT size=2>%s</FONT>',
'<FONT size=3>%s</FONT>',
'<FONT size=4 color=#4352c2><STRONG>%s</STRONG></FONT>',
'<FONT size=5 color=#800080>%s</FONT>',
'<FONT size=5 color=#e2007f><EM><STRONG>%s</STRONG></EM></FONT>',
'<FONT size=5 color=#e2007f><STRONG><EM>%s</EM></STRONG></FONT>',
'<FONT size=6>%s</FONT>',
'<FONT size=7>%s</FONT>',
'<FONT style="BACKGROUND-COLOR: #bcdfff">%s</FONT>',
);

our @html_style2 = (
'<FONT color=#0000cc size=7>%s</FONT>',
'<FONT color=#4352c2 size=6>%s</FONT>',
'<FONT color=#92007b size=6>%s</FONT>',
'<FONT color=#df0029 size=6>%s</FONT>',
'<FONT color=#df0029 size=7>%s</FONT>',
'<FONT color=#e2007f size=6>%s</FONT>',
'<FONT color=#e2007f size=6><EM>%s</EM></FONT>',
'<FONT color=#e7651a size=6>%s</FONT>',
'<FONT face=HGP創英角ﾎﾟｯﾌﾟ体 size=6 color=#009F62>%s</FONT>',
'<FONT face=HGP創英角ﾎﾟｯﾌﾟ体 size=6 color=#666666>%s</FONT>',
'<FONT size=7 color=#800080>%s</FONT>',
'<FONT size=7 color=#e2007f><EM><STRONG>%s</STRONG></EM></FONT>',
'<FONT size=7 color=#e2007f><STRONG><EM>%s</EM></STRONG></FONT>',
'<FONT size=6>%s</FONT>',
'<FONT size=7>%s</FONT>',
);

our @emoji = (
'<img alt="ドキドキ" src="http://stat.ameba.jp/blog/ucs/img/char/char2/031.gif" />',
'<img alt="ラブラブ" src="http://stat.ameba.jp/blog/ucs/img/char/char2/035.gif" />',
'<img alt="音譜" src="http://stat.ameba.jp/blog/ucs/img/char/char2/038.gif" />',
'<img alt="汗" src="http://stat.ameba.jp/blog/ucs/img/char/char2/028.gif" />',
'<img alt="あせる" src="http://stat.ameba.jp/blog/ucs/img/char/char2/029.gif" />',
'<img alt="ビックリマーク" src="http://stat.ameba.jp/blog/ucs/img/char/char2/039.gif" />',
'<img alt="はてなマーク" src="http://stat.ameba.jp/blog/ucs/img/char/char2/040.gif" />',
'<img alt="！！" src="http://stat.ameba.jp/blog/ucs/img/char/char2/176.gif" />',
'<img alt="！？" src="http://stat.ameba.jp/blog/ucs/img/char/char2/177.gif" />',
'<img alt="ビックリマーク" src="http://stat.ameba.jp/blog/ucs/img/char/char2/039.gif" />',
'<img alt="はてなマーク" src="http://stat.ameba.jp/blog/ucs/img/char/char2/040.gif" />',
'<img alt="！！" src="http://stat.ameba.jp/blog/ucs/img/char/char2/176.gif" />',
'<img alt="！？" src="http://stat.ameba.jp/blog/ucs/img/char/char2/177.gif" />',
'<img alt="ビックリマーク" src="http://stat.ameba.jp/blog/ucs/img/char/char2/039.gif" />',
'<img alt="はてなマーク" src="http://stat.ameba.jp/blog/ucs/img/char/char2/040.gif" />',
'<img alt="！！" src="http://stat.ameba.jp/blog/ucs/img/char/char2/176.gif" />',
'<img alt="！？" src="http://stat.ameba.jp/blog/ucs/img/char/char2/177.gif" />',
'<img alt="爆弾" src="http://stat.ameba.jp/blog/ucs/img/char/char2/036.gif" />',
'<img alt="ドンッ" src="http://stat.ameba.jp/blog/ucs/img/char/char2/280.gif" />',
'<img alt="メラメラ" src="http://stat.ameba.jp/blog/ucs/img/char/char2/037.gif" />',
'<img alt="合格" src="http://stat.ameba.jp/blog/ucs/img/char/char2/304.gif" />',
'<img alt="クラッカー" src="http://stat.ameba.jp/blog/ucs/img/char/char2/098.gif" />',
'<img alt="ひらめき電球" src="http://stat.ameba.jp/blog/ucs/img/char/char2/089.gif" />',
'<img alt="目" src="http://stat.ameba.jp/blog/ucs/img/char/char2/242.gif" />',
'<img alt="晴れ" src="http://stat.ameba.jp/blog/ucs/img/char/char2/022.gif" />',
'<img alt="流れ星" src="http://stat.ameba.jp/blog/ucs/img/char/char2/114.gif" />',
'<img alt="ブーケ１" src="http://stat.ameba.jp/blog/ucs/img/char/char2/052.gif" />',
'<img alt="旗" src="http://stat.ameba.jp/blog/ucs/img/char/char2/132.gif" />',
'<img alt="ロケット" src="http://stat.ameba.jp/blog/ucs/img/char/char2/127.gif" />',
'<img alt="雷" src="http://stat.ameba.jp/blog/ucs/img/char/char2/024.gif" />',
'<img alt="グッド！" src="http://stat.ameba.jp/blog/ucs/img/char/char2/187.gif" />',
'<img alt="アップ" src="http://stat.ameba.jp/blog/ucs/img/char/char2/173.gif" />',
'<img alt="グー" src="http://stat.ameba.jp/blog/ucs/img/char/char2/104.gif" />',
'<img alt="流れ星" src="http://stat.ameba.jp/blog/ucs/img/char/char2/114.gif" />',
'<img alt="チューリップ赤" src="http://stat.ameba.jp/blog/ucs/img/char/char2/061.gif" />',
'<img alt="ヒヨコ" src="http://stat.ameba.jp/blog/ucs/img/char/char2/008.gif" />',
'<img alt="ラーメン" src="http://stat.ameba.jp/blog/ucs/img/char/char2/192.gif" />',
'<img alt="プレゼント" src="http://stat.ameba.jp/blog/ucs/img/char/char2/102.gif" />',
'<img alt="カクテルグラス" src="http://stat.ameba.jp/blog/ucs/img/char/char2/069.gif" />',
'<img alt="ビール" src="http://stat.ameba.jp/blog/ucs/img/char/char2/077.gif" />',
'<img alt="ベル" src="http://stat.ameba.jp/blog/ucs/img/char/char2/182.gif" />',
'<img alt="リボン" src="http://stat.ameba.jp/blog/ucs/img/char/char2/169.gif" />',
'<img alt="王冠１" src="http://stat.ameba.jp/blog/ucs/img/char/char2/120.gif" />',
'<img alt="王冠２" src="http://stat.ameba.jp/blog/ucs/img/char/char2/121.gif" />',
'<img alt="旗" src="http://stat.ameba.jp/blog/ucs/img/char/char2/132.gif" />',
'<img alt="桜" src="http://stat.ameba.jp/blog/ucs/img/char/char2/095.gif" />',
);

sub html_fx {
    sprintf $html_style[ int rand @html_style ], shift || "";
}

sub html_fx2 {
    sprintf $html_style2[ int rand @html_style2 ], shift || "";
}

sub html_fx_emoji {
    my $html = html_fx2(shift);
    if (my $emoji = $emoji[ int rand @emoji ]) {
        $html .= $emoji;
    }
    $html;
}

our %lou5 = (
    "ルー語"                                   => "ルー語",
    
    "元気"                                     => "ファイン",
    "一年"                                     => "ワンイヤー",
    "よいお年"                                 => "グッドイヤー",
    "良いお年"                                 => "グッドイヤー",
    "新年"                                     => "ニューイヤー",
    "あけおめ"                                 => "あけおめトゥギャザー",
    "ことよろ"                                 => "ことよろトゥギャザー",
    "明けまして"                               => "明けましてトゥギャザー",
    "あけまして"                               => "あけましてトゥギャザー",
    "よろしく"                                 => "よろしくトゥギャザー",
    "お願いします"                             => "プリーズ",
    
    "水臭い"                                   => "ウォーター臭い",
    "犬も歩けば棒に当たる"                     => "犬もウォークすればポールにヒットする",
    "泣きっ面に蜂"                             => "泣きっ面にビー",
    "やぶから棒"                               => "やぶからスティック",
    "薮から棒"                                 => "薮からスティック",
    "藪から棒"                                 => "藪からスティック",
    "念には念を入れよ"                         => "念には念をプットイン",
    "立て板に水"                               => "立て板にウォーター",
    "青菜に塩"                                 => "青菜にソルト",
    "自己破産"                                 => "バイマイセルフ破産",
    "地球温暖化"                               => "地球ホット化",
    "ちりも積もれば山となる"                   => "トラッシュも積もればマウンテンとなる",
    "知らぬが仏"                               => "ドントノウが仏",
    "論より証拠"                               => "論よりエビデンス",
    "天下り問題"                               => "ヘブン下りプロブレム",
    "負けるが勝ち"                             => "ルーズするがウイン",
    "雨降って地固まる"                         => "レイン降ってアース固まる",
    "石の上にも三年"                           => "ストーンの上にもスリーイヤー",
    "石橋を叩いて渡る"                         => "石橋をタップして渡る",
    "河童の川流れ"                             => "河童のリバー流れ",
    "壁に耳あり、障子に目あり"                 => "壁にイヤーあり、障子にアイズあり",
    "弘法も筆の誤まり"                         => "弘法もペンシルの誤まり",
    "猿も木から落ちる"                         => "猿もツリーからドロッピング",
    "転ばぬ先の杖"                             => "転ばぬ先のステッキ",
    "触らぬ神に祟りなし"                       => "触らぬヘブンに祟りなし",
    "重箱の隅を楊枝でほじくる"                 => "重箱の隅をチョップスティックでほじくる",
    "雀の涙"                                   => "雀のティアー",
    "宝の持ち腐れ"                             => "トレジャーの持ち腐れ",
    "出る杭は打たれる"                         => "出るポールは打たれる",
    "年寄りの冷や水"                           => "オールドの冷やウォーター",
    "長い物には巻かれろ"                       => "長い物にはローリング",
    "二階から目薬"                             => "二階からアイドラッグ",
    "似た者夫婦"                               => "似た者マリードカップル",
    "猫に小判"                                 => "猫にマネー",
    "弁慶の泣き所"                             => "弁慶のクライ所",
    "仏作って魂入れず"                         => "仏作ってソウル入れず",
    "焼け石に水"                               => "焼け石にウォーター",
    "良薬は口に苦し"                           => "良薬はマウスにビター",
    "背に腹はかえられぬ"                       => "背にストマックはかえられぬ",
    "憎まれっ子世に憚る"                       => "バッドボーイ世に憚る",
    "骨折り損の草臥れ儲け"                     => "骨折りロストの草臥れプロフィット",
    "身から出た錆"                             => "ボディから出た錆",
    "安物買いの銭失い"                         => "安物バイの銭ルーズ",
    "旅は道連れ、世は情け"                     => "トラベルは道連れ、世はカインドネス",
    "糠に釘"                                   => "糠にスパイク",
    "酒は百薬の長"                             => "酒はハンドレッドメディスンの長",
    "寝耳に水"                                 => "寝耳にウォーター",
    "頭隠して尻隠さず"                         => "頭ハイドしてヒップ隠さず",
    "楽あれば苦あり"                           => "ファニーあればディフィカルトあり",
    "火中の栗を拾う"                           => "火中のマロンを拾う",
    "鬼に金棒"                                 => "デビルに金棒",
    "芸は身を助ける"                           => "芸はボディをヘルプする",
    "匙を投げる"                               => "スプーンを投げる",
    "死人に口なし"                             => "死人にマウスなし",
    "能ある鷹は爪を隠す"                       => "能あるホークはネイルを隠す",
    "仏の顔も三度"                             => "仏のフェイスもスリータイムズ",
    "爪に火をともす"                           => "ネイルにファイヤーをともす",
    "一寸先は闇"                               => "一寸アフターはダーク",
    "焼け石に水"                               => "焼けストーンにウォーター",
    "溺れるものは藁をも掴む"                   => "溺れるものはストローをも掴む",
    "下流"                                     => "ローリバー",
    "幼児虐待"                                 => "幼児バイオレンス",
    "超うざい"                                 => "ベリーうざい",
    "改正"                                     => "リフォーム",
    "破綻"                                     => "メルトダウン",
    "不払い問題"                               => "ノーペイ",
    "統合"                                     => "トゥギャザー",
    "風の噂"                                   => "ウィンドの噂",
    "殺してしまえ"                             => "キルしてしまえ",
    "鳴かせてみせよう"                         => "メイク・シングさせよう",
    "鳴くまで待とう"                           => "ウェイトしよう",
    "渡りに船"                                 => "渡りにシップ",
    "赤子の手をひねる"                         => "ベビーの手をひねる",
    "揚げ足をとる"                             => "揚げフットをとる",
    "当たって砕けよ"                           => "アタックして砕けよ",
    "水と油"                                   => "ウォーターとオイル",
    "残り物には福がある"                       => "残り物にはハッピーがある",
    "言うは易し、行うは難し"                   => "言うはイージー、行うはディフィカルト",
    "いざ鎌倉"                                 => "カモン鎌倉",
    "一富士二鷹三茄子"                         => "ワン富士ツー鷹スリー茄子",
    "犬が西向きゃ尾は東"                       => "ドッグが西向きゃテイルは東",
    "後ろ髪を引かれる"                         => "後ろヘアーを引かれる",
    "後ろ指を指される"                         => "後ろフィンガーを指される",
    "売り言葉に買い言葉"                       => "セル言葉にバイ言葉",
    "絵に描いた餅"                             => "ピクチャに描いたライスケーキ",
    "お茶を濁す"                               => "ティーを濁す",
    "思い立ったが吉日"                         => "思い立ったがラッキーデー",
    "親の心子知らず"                           => "親の心子ドントノウ",
    "木を見て森を見ず"                         => "木をルックして森をドントルック",
    "犬猿の仲"                                 => "ドッグモンキーの仲",
    "子の心親知らず"                           => "子の心親ドントノウ",
    "案ずるより産むが易し"                     => "ウォーリーより産むがイージー",
    "顔を洗って出直す"                         => "フェイスを洗ってカムバック",
    "かわいい子には旅させよ"                   => "ラブリーな子にはトリップさせよ",
    "後の祭り"                                 => "後のフェスティバル",
    "十人十色"                                 => "十人テンカラー",
    "覆水盆に返らず"                           => "覆水ノーリターン",
    "ゆく年くる年"                             => "ゴゥするイヤー、カムするイヤー",
    "目は口ほどに物を言う"                     => "目はマウスほどに物をセイ",
    "急がば回れ"                               => "急がばスピン",
    "果報は寝て待て"                           => "ラッキーは寝てウェイト",
    "月とすっぽん"                             => "ムーンとスッポン",
    "花より団子"                               => "フラワーより団子",
    "下手な鉄砲も数打ちゃ当たる"               => "下手なピストルも数打ちゃヒットする",
    "鬼"                                       => "デビル",
    "井の中の蛙大海を知らず"                   => "井の中のフロッグ大海をドントノウ",
    "雲泥の差"                                 => "雲泥のディファレンス",
    "蛙の子は蛙"                               => "フロッグの子はフロッグ",
    "苦しい時の神頼み"                         => "苦しい時のヘブン頼み",
    "弘法筆を選ばず"                           => "弘法ペンシルを選ばず",
    "賽は投げられた"                           => "ダイスは投げられた",
    "捨てる神あれば拾う神あり"                 => "捨てるヘブンあれば拾うヘブンあり",
    "沈黙は金、雄弁は銀"                       => "沈黙はゴールド、雄弁はシルバー",
    "爪の垢を煎じて飲む"                       => "ネイルの垢を煎じてドリンク",
    "鉄は熱いうちに打て"                       => "アイロンは熱いうちにヒット",
    "八方塞がり"                               => "エイトウェイ塞がり",
    "鳩に豆鉄砲"                               => "鳩に豆ピストル",
    "秋茄子は嫁に食わすな"                     => "オータム茄子はワイフに食わすな",
    "後は野となれ山となれ"                     => "後はフィールドとなれマウンテンとなれ",
    "一姫二太郎"                               => "ワン姫ツー太郎",
    "嘘からでた真"                             => "ライから出たトゥルー",
    "飼い犬に手をかまれる"                     => "ペット犬にハンドをかまれる",
    "夫婦喧嘩は犬も食わない"                   => "マリードカップル喧嘩は犬もドントイート",
    "馬子にも衣装"                             => "馬子にもドレス",
    "虎の威を借る狐"                           => "タイガーの威を借るフォックス",
    "雀百まで踊り忘れず"                       => "スパロー百までダンス忘れず",
    "猫も杓子も"                               => "猫もスプーンも",
    "豚に真珠"                                 => "豚にパール",
    "猫の手も借りたい"                         => "猫のハンドもレンタルしたい",
    "立つ鳥跡を濁さず"                         => "リービングバード跡を濁さず",
    "早起きは三文の徳"                         => "早ウェイクアップは三文のプロフィット",
    "親の七光"                                 => "親のセブンライツ",
    "笑う門には福来たる"                       => "笑うゲートには福カモン",
    "五十歩百歩"                               => "五十フット百フット",
    "三歩進んで、二歩下がる"                   => "スリーフット進んで、ツーフットバック",
    "詰めが甘い"                               => "詰めがスウィート",
    "記憶にございません"                       => "メモリーにございません",
    "同情するなら金をくれ"                     => "同情するならマネーをくれ",
    "豚もおだてりゃ木に登る"                   => "ピッグもおだてりゃツリーに登る",
    "耳にタコができる程聞いた"                 => "イヤーにオクトパスができる程リッスンした",
    "豚に真珠"                                 => "ピッグにパール",
    "金は天下の回りもの"                       => "マネーは天下のスピンもの",
    "木を見て森を見ず"                         => "トゥリーを見てフォレスト見ず",
    "早起きは三文の徳"                         => "早起きはスリーダラーゲット",
    "器用貧乏"                                 => "器用プア",
    "一人旅"                                   => "アローン旅",
    "他人の空似"                               => "他人のスカイ似",
    "芋焼酎"                                   => "ポテト焼酎",
    "私事"                                     => "ミー事",
    "隠し子"                                   => "ハイド子",
    "一石二鳥"                                 => "一ストーン二バード",
    "紅白歌合戦"                               => "レッドホワイト歌合戦",
    "山あり谷あり"                             => "マウンテンありヴァレーあり",
    "うたた寝"                                 => "うたたスリープ",
    "うずらの卵"                               => "うずらのエッグ",
    "虫の知らせ"                               => "虫のインフォメーション",
    "果報は寝て待て"                           => "果報はグッナイして待て",
    "犬も歩けば棒に当たる"                     => "ドッグも歩けばスティックにヒット",
    "千の風になって"                           => "サウザンドのウィンドになって",
    "鶴の一声"                                 => "鶴のワンボイス",
    "親馬鹿"                                   => "ペアレント馬鹿",
    "穴があったら入りたい"                     => "ホールがあったら入りたい",
    "面目が丸潰れ"                             => "フェイスが丸ブロークン",
    "火のないところに煙は立たぬ"               => "ファイヤーのないところにスモークは立たぬ",
    "危機一髪"                                 => "クライシス一髪",
    "汗と涙の結晶"                             => "スウェットとティアーの結晶",
    "机上の空論"                               => "空論オンザデスク",
    "天下り"                                   => "ヘブン下り",
);

our $lou5_re = do {
    my $w = join "|", keys %lou5;
    qr/($w)/;
};

1;
